### ISSUE TITLE
Code completion modifies indentation and has odd entry points

### ISSUE THREAD

**Issue by colinstark** [raulchedrese/nova-elixir-ls#15]
This shows the behaviour: 
![code-completion](https://user-images.githubusercontent.com/5658185/138495930-0cc567c9-41d7-4545-9ee9-bfa627dcb308.gif)

while it adds an `end` tag, it deletes whitespace and then sets the cursor to a weird place... after tab it focusses on the defition name, but getting to definition content is not available via tab.

**Comment by colinstark** [comment]
the behaviour is the same with tabs instead of spaces. it just seems to reset any preceding whitespace at the current line.

![tabs](https://user-images.githubusercontent.com/5658185/138497790-0a65f6f8-5f9a-4e61-8e4e-aa9d0249e1e8.gif)

**Comment by raulchedrese** [comment]
Hey Colin, thanks for taking the time to open an issue! I've noticed this issue also. This code completion is handled by [ElixirLS](https://github.com/elixir-lsp/elixir-ls) and it looks like Nova is interpreting the completion returned by ElixirLS differently than other editors do. We'll need to figure out what is causing that difference and either open an issue on the ElixirLS repo or report a bug in Nova.

If you are interested in attempting a fix please do! Otherwise I'll take a look when I can a chance but it likely won't be soon.
