### ISSUE TITLE
Notification: LS not receiving workspace/didChangeConfiguration

### ISSUE THREAD

**Issue by colinstark** [raulchedrese/nova-elixir-ls#16]
`Did not receive workspace/didChangeConfiguration notification after 5 seconds. Using default settings.`
This shows up on every initialization.

<img width="344" alt="Shot 2021-10-22 at 19 06 19" src="https://user-images.githubusercontent.com/5658185/138496331-4a63d0f0-a52d-4f62-b58f-c3def0362a61.png">

**Comment by colinstark** [comment]
If this is constantly checking in the background, it could be related to another issue I have, and that is beam going crazy without me running a process either in Nova or terminal (so I assume it's the LS causing it)
<img width="269" alt="cpu" src="https://user-images.githubusercontent.com/5658185/138496474-18c6527e-dd50-46fd-a656-916ea71fe5ee.png">

**Comment by raulchedrese** [comment]
Hey Colin, thanks for the bug report! I'm not sure why you are seeing that alert since the `workspace/didChangeConfiguration` notification is being dispatched [here](https://github.com/raulchedrese/nova-elixir-ls/blob/master/src/ElixirLanguageServer.ts#L44). We'll need to debug why the language server isn't receiving it. I likely won't be able to get to it soon so feel free to dive in and take look if you are interested.

The second issue you are seeing seems to be a known issue with ElixirLS but should only occur when the project is first opened. Are you seeing the CPU usage go back down to normal after a few minutes?

**Comment by lessless** [comment]
I do receive those messages from time to time and will keep an eye on the debug output.

**Comment by raulchedrese** [comment]
Hey folks, I believe this is resolved in the latest version of Nova. Let me know if you are still seeing it in the latest version of Nova with the latest version of the extension.

**Comment by colinstark** [comment]
It's not showing up anymore for me - thank you!
